# Welcome to Jekyll!
#
# About Theme
#
# Yet another theme for elegant writers with modern flat style and beautiful
# night/dark mode.
#
# Website: https://github.com/jeffreytse/jekyll-theme-yat
#
# You can do anything you want, including projects for your clients, as long
# as you mention an attribution back (credit links in footer or project).
# See the LICENCE file.
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when you
# use 'bundle exec jekyll serve'. If you change this file, please restart
# the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Brazacz blog
# email: your-email@domain.com
author: brazacz
copyright: Copyright © 2021-2025
description: >- # this means to ignore newlines until "baseurl:"
  I'm just an amateur coder who likes learning new things and sharing them with others.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.brazacz.com" # the base hostname & protocol for your site, e.g. https://example.com
favicon_ico: "/favicon.ico" # the favicon for your site (with .ico extension)
favicon_svg: "/favicon.svg" # the favicon for your site (with .svg extension)
github_link: https://github.com/brazacz

# Yat date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
yat:
  date_format: "%b %d, %Y"

# If you want more debug log, you can set true
# debug: false

# If you don't want transparent header, you can set false
header_transparent: false

# Google analytics
# google_analytics: [Tracking ID]

# If you want to generate website sitemap, you can set true
# sitemap: false

# If you want to change site language, you can set lang option
# lang: "en"  # default lang is en

# Translate languges
# langs refer to https://cloud.google.com/translate/docs/languages
# translate_langs:
#   - lang: en
#     text: English
#
#   - lang: fr
#     img: https://www.countryflags.io/fr/flat/64.png
#     text: Franch
#
#   - lang: zh-CN
#     img: https://www.countryflags.io/cn/flat/64.png
#     text: Chinese(Simple)
#
#   - lang: zh-TW
#     img: https://www.countryflags.io/tw/flat/64.png
#     text: Chinese(Traditional)
#
#   - lang: ja
#     img: https://www.countryflags.io/jp/flat/64.png
#     text: Japan
#
#   - lang: ko
#     img: https://www.countryflags.io/kr/flat/64.png
#     text: Korean
#
#   - lang: ru
#     img: https://www.countryflags.io/ru/flat/64.png
#     text: Russia

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is"manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
#
# night_mode: "auto"

# Code badge setting
# You can enable or disable the code badge and so on
code_badge:
  enabled: "true"
  color: "#fff"
  background_color: "#748b95"
  text_transform: "capitalize"  # ("uppercase", "lowercase", "capitalize")

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - index.html
  - about.md
  - archives.html
  - tags.html
#   - categories.html

# Page default value
defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: "/blog/:title"
  - scope:
      path: "_drafts"
    values:
      layout: "post"
      permalink: "/blog/:title"
#   home:
#     heading: "Your awesome heading"
#     subheading: "Your awesome subheading"
#     banner: "Your image url"

# Excerpt size setting
# excerpt_size: 350

# Pagination setting
# paginate: 5

# Disqus comments
# disqus:
#   shortname: "Your Disqus username"

# Gitment comments
# gitment:
#   username: "Your GitHub username"
#   repo: "The repo to store comments"
#   client_id: "Your client ID"
#   client_secret: "Your client secret"
#   redirect_uri: "Your redirect url"   # If you use a custom domain name

# Build settings
# highlighter: none
markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
